import customAxios from "./axios";

// axios.get("https://google.com/search/q=Hey+there")
// customAxios.getting("/", undefined)
//     .then(res => console.log(res))
//     .catch(err => console.error(err))

export const foods = [

    {
        "name": "Naan",
        "calories": 262,
        "protien": 8.7,
        "carbohydrates": 45,
        "fat": 5.1,
        "sodium": 1,
        "fiber": 1.5,
        "sugars": 3.2,
        "calcium": 76,
        "iron": 2.9,
        "potassium": 112.5,
        "cholestrol": 45,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Paneer Tikka",
        "calories": 201,
        "protien": 8.2,
        "carbohydrates": 6.9,
        "fat": 16,
        "sodium": 41,
        "fiber": "2g",
        "sugars": 3.7,
        "calcium": 224,
        "iron": 0.9,
        "potassium": 290.6,
        "cholestrol": 41,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Pani Puri",
        "calories": 152,
        "protien": 2.5,
        "carbohydrates": 15,
        "fat": 9.9,
        "sodium": 110,
        "fiber": 2.2,
        "sugars": 1.9,
        "calcium": 14,
        "iron": 1,
        "potassium": 90.3,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Pav Bhaji",
        "calories": 390,
        "protien": 12,
        "carbohydrates": 63,
        "fat": 11,
        "sodium": 589,
        "fiber": 5,
        "sugars": 11,
        "calcium": 124,
        "iron": 5.7,
        "potassium": 813,
        "cholestrol": 50,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Vadapav",
        "calories": 263,
        "protien": 7.5,
        "carbohydrates": 37,
        "fat": 9.5,
        "sodium": 209,
        "fiber": 3.8,
        "sugars": 3.5,
        "calcium": 36,
        "iron": 2.1,
        "potassium": 357.3,
        "cholestrol": 18,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Dal",
        "calories": 222,
        "protien": 14,
        "carbohydrates": 34,
        "fat": "4.2g",
        "sodium": 431,
        "fiber": 13,
        "sugars": 4.5,
        "calcium": 44,
        "iron": 5.8,
        "potassium": 713.2,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Dhokla",
        "calories": 152,
        "protien": 5.7,
        "carbohydrates": 16,
        "fat": 7.4,
        "sodium": 310,
        "fiber": 2.5,
        "sugars": 5.7,
        "calcium": 42,
        "iron": 1.2,
        "potassium": 240.5,
        "cholestrol": 3.3,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Dosa",
        "calories": 168,
        "protien": 3.9,
        "carbohydrates": 29,
        "fat": 3.7,
        "sodium": 94,
        "fiber": 0.9,
        "sugars": 0.2,
        "calcium": 5.7,
        "iron": 0.8,
        "potassium": 75.6,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Pakora",
        "calories": 95,
        "protien": 2.2,
        "carbohydrates": 6.5,
        "fat": 7,
        "sodium": 180,
        "fiber": 1.5,
        "sugars": 1.9,
        "calcium": 12.5,
        "iron": 0.6,
        "potassium": 118.5,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Cucumber",
        "calories": 30,
        "protien": 1.3,
        "carbohydrates": 11,
        "fat": 0.3,
        "sodium": 4,
        "fiber": 1.5,
        "sugars": 3.4,
        "calcium": 32,
        "iron": 0.6,
        "potassium": 295.5,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Potato",
        "calories": 161,
        "protien": 4.3,
        "carbohydrates": 37,
        "fat": 0.2,
        "sodium": 17,
        "fiber": 3.8,
        "sugars": 2,
        "calcium": 26,
        "iron": 1.9,
        "potassium": 925.6,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Carrot",
        "calories": 16,
        "protien": 0.4,
        "carbohydrates": 3.8,
        "fat": 0.1,
        "sodium": 27,
        "fiber": 1.4,
        "sugars": 1.6,
        "calcium": 14,
        "iron": 0.2,
        "potassium": 108.1,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Cauliflower",
        "calories": 27,
        "protien": 2.1,
        "carbohydrates": 5.3,
        "fat": 0.3,
        "sodium": 32,
        "fiber": 2.1,
        "sugars": 2,
        "calcium": 24,
        "iron": 0.5,
        "potassium": 319.9,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Corn",
        "calories": 99,
        "protien": 3.5,
        "carbohydrates": 22,
        "fat": 1.5,
        "sodium": 1,
        "fiber": 2.5,
        "sugars": 4.7,
        "calcium": 3.1,
        "iron": 0.5,
        "potassium": 224.5,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurementment": "piece"
    },
    {
        "name": "Watermelon",
        "calories": 86,
        "protien": 1.7,
        "carbohydrates": 22,
        "fat": 0.4,
        "sodium": 2.9,
        "fiber": 1.1,
        "sugars": 18,
        "calcium": 20,
        "iron": 0.7,
        "potassium": 320.3,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurementment": "piece"
    },
    {
        "name": "Orange",
        "calories": 69,
        "protien": 1.3,
        "carbohydrates": 18,
        "fat": 0.2,
        "sodium": 1.4,
        "fiber": 3.1,
        "sugars": 12,
        "calcium": 60,
        "iron": 0.2,
        "potassium": 232.4,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurement": "piece"
    },
    {
        "name": "Pomegranate",
        "calories": 234,
        "protien": 4.7,
        "carbohydrates": 53,
        "fat": 3.3,
        "sodium": 8.5,
        "fiber": 11,
        "sugars": 39,
        "calcium": 28,
        "iron": 0.9,
        "potassium": 665.5,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurement": "piece"
    },
    {
        "name": "Radish",
        "calories": 16.6,
        "protien": 0.7,
        "carbohydrates": 3.5,
        "fat": 0,
        "sodium": 41.4,
        "fiber": 1.6,
        "sugars": 1.8,
        "calcium": 25.3,
        "iron": 0.5,
        "potassium": 241.2,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Papaya",
        "calories": 62,
        "protien": 0.7,
        "carbohydrates": 16,
        "fat": 0.4,
        "sodium": 12,
        "fiber": 2.5,
        "sugars": 11,
        "calcium": 29,
        "iron": 0.4,
        "potassium": 263.9,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurement": "piece"
    },
    {
        "name": "Banana",
        "calories": 105,
        "protien": 1.3,
        "carbohydrates": 27,
        "fat": 0.4,
        "sodium": 1.2,
        "fiber": 3.1,
        "sugars": 14,
        "calcium": 5.9,
        "iron": 0.3,
        "potassium": 422.4,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurement": "piece"
    },
    {
        "name": "Apple",
        "calories": 95,
        "protien": 0.5,
        "carbohydrates": 25,
        "fat": 0.3,
        "sodium": 1.8,
        "fiber": 4.4,
        "sugars": 19,
        "calcium": 11,
        "iron": 0.2,
        "potassium": 194.7,
        "cholestrol": 0,
        "Food Type": "Fruit",
        "measurement": "piece"
    },
    {
        "name": "Tomato",
        "calories": 22,
        "protien": 1.1,
        "carbohydrates": 4.8,
        "fat": 0.3,
        "sodium": 6.2,
        "fiber": 1.5,
        "sugars": 3.2,
        "calcium": 12,
        "iron": 0.3,
        "potassium": 291.5,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Brocolli",
        "calories": 3.5,
        "protien": 0.2,
        "carbohydrates": 0.7,
        "fat": 0.3,
        "sodium": 4.1,
        "fiber": 0.3,
        "sugars": 0.1,
        "calcium": 4,
        "iron": 0.1,
        "potassium": 29.3,
        "cholestrol": 0,
        "Food Type": "Vegetable",
        "measurement": "piece"
    },
    {
        "name": "Baked Potato",
        "calories": 161,
        "protien": 4.3,
        "carbohydrates": 37,
        "fat": 0.2,
        "sodium": 17,
        "fiber": 3.8,
        "sugars": 2,
        "calcium": 26,
        "iron": 1.9,
        "potassium": 925.6,
        "cholestrol": 0,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Burger",
        "calories": 540,
        "protien": 34,
        "carbohydrates": 40,
        "fat": 27,
        "sodium": 791,
        "fiber": 0,
        "sugars": 0,
        "calcium": 102,
        "iron": 5.9,
        "potassium": 569.5,
        "cholestrol": 122,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Crispy Chicken",
        "calories": 377,
        "protien": 40,
        "carbohydrates": 4.4,
        "fat": 21,
        "sodium": 118,
        "fiber": 0.1,
        "sugars": 0,
        "calcium": 24,
        "iron": 1.9,
        "potassium": 327.6,
        "cholestrol": 126,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Donut",
        "calories": 253,
        "protien": 3.7,
        "carbohydrates": 29,
        "fat": 14,
        "sodium": 190,
        "fiber": 1.3,
        "sugars": 14,
        "calcium": 61,
        "iron": 1.4,
        "potassium": 61.2,
        "cholestrol": 18,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "French Fries",
        "calories": 365,
        "protien": 4,
        "carbohydrates": 48,
        "fat": 17,
        "sodium": 246,
        "fiber": 4.4,
        "sugars": 0.4,
        "calcium": 21,
        "iron": 1,
        "potassium": 677.4,
        "cholestrol": 100,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Hot Dog",
        "calories": 155,
        "protien": 5.6,
        "carbohydrates": 1.3,
        "fat": 14,
        "sodium": 409,
        "fiber": 0,
        "sugars": 0.6,
        "calcium": 5.3,
        "iron": 0.6,
        "potassium": 121,
        "cholestrol": 28,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Pizza",
        "calories": 285,
        "protien": 12,
        "carbohydrates": 36,
        "fat": 10,
        "sodium": 640,
        "fiber": 2.5,
        "sugars": 3.8,
        "calcium": 201,
        "iron": 2.7,
        "potassium": 184,
        "cholestrol": 18,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Sandwich",
        "calories": 310,
        "protien": 12.4,
        "carbohydrates": 56,
        "fat": 3.8,
        "sodium": 590,
        "fiber": 4.6,
        "sugars": 6.8,
        "calcium": 154,
        "iron": 4,
        "potassium": 205.3,
        "cholestrol": 0,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Taco",
        "calories": 210,
        "protien": 9.4,
        "carbohydrates": 21,
        "fat": 9.9,
        "sodium": 571,
        "fiber": 3,
        "sugars": 1.6,
        "calcium": 125,
        "iron": 1.7,
        "potassium": 164.2,
        "cholestrol": 26,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Taquito",
        "calories": 120,
        "protien": 3.9,
        "carbohydrates": 14,
        "fat": 5.3,
        "sodium": 191,
        "fiber": 1.2,
        "sugars": 0.6,
        "calcium": 42,
        "iron": 1.1,
        "potassium": 69.1,
        "cholestrol": 5,
        "Food Type": "Junk Food",
        "measurement": "piece"
    },
    {
        "name": "Dabeli",
        "calories": 219,
        "protien": 4.2,
        "carbohydrates": 31.6,
        "fat": 8.3,
        "sodium": 60.6,
        "fiber": 0.3,
        "sugars": 4,
        "calcium": 26.8,
        "iron": 1,
        "potassium": 66.2,
        "cholestrol": 7.5,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Samosa",
        "calories": 261,
        "protien": 3.5,
        "carbohydrates": 24,
        "fat": 17,
        "sodium": 423,
        "fiber": 2.1,
        "sugars": 1.6,
        "calcium": 17,
        "iron": 0.7,
        "potassium": 189.1,
        "cholestrol": 27,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Idli",
        "calories": 174,
        "protien": 4.8,
        "carbohydrates": 36,
        "fat": 1.3,
        "sodium": 225,
        "fiber": 1.6,
        "sugars": 0.3,
        "calcium": 30,
        "iron": 1.8,
        "potassium": 123.3,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Chai",
        "calories": 4.9,
        "protien": 0.1,
        "carbohydrates": 1.4,
        "fat": 0.1,
        "sodium": 0.8,
        "fiber": 0.3,
        "sugars": 0,
        "calcium": 5.9,
        "iron": 0.1,
        "potassium": 57.7,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "cup"
    },
    {
        "name": "Fried Rice",
        "calories": 279,
        "protien": 8,
        "carbohydrates": 30,
        "fat": 14,
        "sodium": 363,
        "fiber": 2.1,
        "sugars": 2.2,
        "calcium": 37,
        "iron": 1.1,
        "potassium": 205.6,
        "cholestrol": 88,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Aloo Gobi",
        "calories": 160,
        "protien": 2.5,
        "carbohydrates": 10.5,
        "fat": 1,
        "sodium": 400,
        "fiber": 3,
        "sugars": 2,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 320,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Aloo Matar",
        "calories": 180,
        "protien": 3,
        "carbohydrates": 12,
        "fat": 1.5,
        "sodium": 350,
        "fiber": 3.5,
        "sugars": 2.5,
        "calcium": 35,
        "iron": 1.6,
        "potassium": 330,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Aloo Methi",
        "calories": 170,
        "protien": 2.2,
        "carbohydrates": 16,
        "fat": 5.4,
        "sodium": 300,
        "fiber": 2.8,
        "sugars": 2,
        "calcium": 40,
        "iron": 1.2,
        "potassium": 310,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Aloo Shimla Mirch",
        "calories": 150,
        "protien": 1.5,
        "carbohydrates": 12.8,
        "fat": 3.4,
        "sodium": 250,
        "fiber": 3.2,
        "sugars": 2.2,
        "calcium": 25,
        "iron": 1.3,
        "potassium": 300,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Aloo Tikki",
        "calories": 190,
        "protien": 1.8,
        "carbohydrates": 11.8,
        "fat": 5.2,
        "sodium": 350,
        "fiber": 2.5,
        "sugars": 1.5,
        "calcium": 20,
        "iron": 1,
        "potassium": 250,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Anarsa",
        "calories": 180,
        "protien": 30,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 10,
        "fiber": 1,
        "sugars": 20,
        "calcium": 20,
        "iron": 1,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Ariselu",
        "calories": 220,
        "protien": 35,
        "carbohydrates": 3,
        "fat": 9,
        "sodium": 15,
        "fiber": 2,
        "sugars": 25,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 60,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Bandar Laddu",
        "calories": 200,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 8,
        "sodium": 20,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": 50,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Basundi",
        "calories": 250,
        "protien": 35,
        "carbohydrates": 8,
        "fat": 10,
        "sodium": 100,
        "fiber": 0,
        "sugars": 30,
        "calcium": 200,
        "iron": 0.5,
        "potassium": 150,
        "cholestrol": 30,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Bhatura",
        "calories": 300,
        "protien": 7,
        "carbohydrates": 50,
        "fat": 10,
        "sodium": 400,
        "fiber": 2,
        "sugars": 2,
        "calcium": 40,
        "iron": 3,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Bhindi Masala",
        "calories": 161,
        "protien": 3.9,
        "carbohydrates": 12.1,
        "fat": 10.7,
        "sodium": 200,
        "fiber": 4,
        "sugars": 3,
        "calcium": 50,
        "iron": 1.5,
        "potassium": 300,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Biryani",
        "calories": 300,
        "protien": 10,
        "carbohydrates": 40,
        "fat": 10,
        "sodium": 500,
        "fiber": 3,
        "sugars": 5,
        "calcium": 100,
        "iron": 3,
        "potassium": 400,
        "cholestrol": 40,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Boondi",
        "calories": 450,
        "protien": 50,
        "carbohydrates": 10,
        "fat": 25,
        "sodium": 200,
        "fiber": 2,
        "sugars": 20,
        "calcium": 50,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Butter Chicken",
        "calories": 490,
        "protien": 30,
        "carbohydrates": 12,
        "fat": 30,
        "sodium": 600,
        "fiber": 2,
        "sugars": 6,
        "calcium": 150,
        "iron": 2,
        "potassium": 500,
        "cholestrol": 120,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Chak Hao Kheer",
        "calories": 220,
        "protien": 35,
        "carbohydrates": 6,
        "fat": 6,
        "sodium": 50,
        "fiber": 2,
        "sugars": 20,
        "calcium": 100,
        "iron": 1.5,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Cham Cham",
        "calories": 150,
        "protien": 20,
        "carbohydrates": 3,
        "fat": 7,
        "sodium": 20,
        "fiber": 0,
        "sugars": 18,
        "calcium": 40,
        "iron": 0.5,
        "potassium": 80,
        "cholestrol": 15,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Chana Masala",
        "calories": 150,
        "protien": 7,
        "carbohydrates": 25,
        "fat": 3,
        "sodium": 300,
        "fiber": 7,
        "sugars": 6,
        "calcium": 100,
        "iron": 3,
        "potassium": 400,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Chhena Kheeri",
        "calories": 220,
        "protien": 35,
        "carbohydrates": 6,
        "fat": 6,
        "sodium": 50,
        "fiber": 2,
        "sugars": 20,
        "calcium": 1.5,
        "iron": 100,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Chicken Razala",
        "calories": 150,
        "protien": 20,
        "carbohydrates": 3,
        "fat": 7,
        "sodium": 20,
        "fiber": 0,
        "sugars": 18,
        "calcium": 0.5,
        "iron": 40,
        "potassium": 80,
        "cholestrol": 15,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Chicken Tikka",
        "calories": 260,
        "protien": 30,
        "carbohydrates": 5,
        "fat": 10,
        "sodium": 500,
        "fiber": 2,
        "sugars": 2,
        "calcium": 50,
        "iron": 1.5,
        "potassium": 300,
        "cholestrol": 90,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Chicken Tikka Masala",
        "calories": 500,
        "protien": 30,
        "carbohydrates": 15,
        "fat": 35,
        "sodium": 600,
        "fiber": 3,
        "sugars": 6,
        "calcium": 100,
        "iron": 2,
        "potassium": 400,
        "cholestrol": 120,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Chikki",
        "calories": 150,
        "protien": 3,
        "carbohydrates": 20,
        "fat": 7,
        "sodium": 100,
        "fiber": 2,
        "sugars": 15,
        "calcium": 30,
        "iron": 1,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Daal Puri",
        "calories": 150,
        "protien": 20,
        "carbohydrates": 5,
        "fat": 5,
        "sodium": 200,
        "fiber": 2,
        "sugars": 2,
        "calcium": 30,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Unni Appam",
        "calories": 100,
        "protien": 15,
        "carbohydrates": 1,
        "fat": 5,
        "sodium": 10,
        "fiber": 1,
        "sugars": 10,
        "calcium": 20,
        "iron": 0.5,
        "potassium": 40,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Sutar Feni",
        "calories": 150,
        "protien": 25,
        "carbohydrates": 1,
        "fat": 5,
        "sodium": 10,
        "fiber": 0,
        "sugars": 15,
        "calcium": 10,
        "iron": 0.5,
        "potassium": 30,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Sohan Papdi",
        "calories": 200,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 10,
        "sodium": 30,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": 60,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Sohan Halwa",
        "calories": 250,
        "protien": 40,
        "carbohydrates": 4,
        "fat": 10,
        "sodium": 50,
        "fiber": 2,
        "sugars": 20,
        "calcium": 60,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 15,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Shrikhand",
        "calories": 465,
        "protien": 10,
        "carbohydrates": 60,
        "fat": 20,
        "sodium": 150,
        "fiber": 0,
        "sugars": 45,
        "calcium": 100,
        "iron": 0.5,
        "potassium": 100,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "bole"
    },
    {
        "name": "Sheera",
        "calories": 200,
        "protien": 4,
        "carbohydrates": 30,
        "fat": 8,
        "sodium": 150,
        "fiber": 2,
        "sugars": 20,
        "calcium": 40,
        "iron": 1.5,
        "potassium": 100,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Sheer Korma",
        "calories": 300,
        "protien": 45,
        "carbohydrates": 8,
        "fat": 10,
        "sodium": 150,
        "fiber": 2,
        "sugars": 35,
        "calcium": 100,
        "iron": 1.5,
        "potassium": 200,
        "cholestrol": 40,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Shankarpali",
        "calories": 120,
        "protien": 15,
        "carbohydrates": 2,
        "fat": 6,
        "sodium": 20,
        "fiber": 1,
        "sugars": 8,
        "calcium": 40,
        "iron": 0.5,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Sandesh",
        "calories": 350,
        "protien": 12,
        "carbohydrates": 45,
        "fat": 15,
        "sodium": 100,
        "fiber": 0.5,
        "sugars": 35,
        "calcium": 100,
        "iron": 0.5,
        "potassium": 100,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Rasgulla",
        "calories": 200,
        "protien": 5,
        "carbohydrates": 45,
        "fat": 0.5,
        "sodium": 50,
        "fiber": 0.5,
        "sugars": 35,
        "calcium": 100,
        "iron": 1,
        "potassium": 50,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Ras Malai",
        "calories": 250,
        "protien": 30,
        "carbohydrates": 6,
        "fat": 15,
        "sodium": 100,
        "fiber": 0,
        "sugars": 25,
        "calcium": 200,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 100,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Poornalu",
        "calories": 280,
        "protien": 40,
        "carbohydrates": 5,
        "fat": 10,
        "sodium": 50,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1.5,
        "potassium": 100,
        "cholestrol": 50,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Pootharekulu",
        "calories": 220,
        "protien": 25,
        "carbohydrates": 3,
        "fat": 12,
        "sodium": 20,
        "fiber": 0,
        "sugars": 15,
        "calcium": 30,
        "iron": 1,
        "potassium": 120,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Qubani Ka Meetha",
        "calories": 300,
        "protien": 60,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 50,
        "fiber": 2,
        "sugars": 40,
        "calcium": 20,
        "iron": 1.5,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Rabri",
        "calories": 250,
        "protien": 30,
        "carbohydrates": 8,
        "fat": 12,
        "sodium": 100,
        "fiber": 0,
        "sugars": 25,
        "calcium": 200,
        "iron": 0.5,
        "potassium": 150,
        "cholestrol": 30,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Pithe",
        "calories": 200,
        "protien": 35,
        "carbohydrates": 4,
        "fat": 5,
        "sodium": 100,
        "fiber": 2,
        "sugars": 15,
        "calcium": 60,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Poha",
        "calories": 250,
        "protien": 40,
        "carbohydrates": 6,
        "fat": 7,
        "sodium": 300,
        "fiber": 4,
        "sugars": 4,
        "calcium": 20,
        "iron": 4,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Phirni",
        "calories": 230,
        "protien": 35,
        "carbohydrates": 6,
        "fat": 7,
        "sodium": 100,
        "fiber": 1,
        "sugars": 20,
        "calcium": 200,
        "iron": 1,
        "potassium": 150,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Navrattan Korma",
        "calories": 300,
        "protien": 35,
        "carbohydrates": 10,
        "fat": 15,
        "sodium": 400,
        "fiber": 6,
        "sugars": 8,
        "calcium": 150,
        "iron": 2.5,
        "potassium": 400,
        "cholestrol": 15,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Paneer Butter Masala",
        "calories": 400,
        "protien": 15,
        "carbohydrates": 15,
        "fat": 30,
        "sodium": 600,
        "fiber": 3,
        "sugars": 6,
        "calcium": 300,
        "iron": 3,
        "potassium": 250,
        "cholestrol": 50,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Palak Paneer",
        "calories": 280,
        "protien": 12,
        "carbohydrates": 12,
        "fat": 20,
        "sodium": 500,
        "fiber": 4,
        "sugars": 4,
        "calcium": 250,
        "iron": 4,
        "potassium": 450,
        "cholestrol": 35,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Mysore Pak",
        "calories": 250,
        "protien": 30,
        "carbohydrates": 3,
        "fat": 15,
        "sodium": 50,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": "",
        "cholestrol": 50,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Modak",
        "calories": 150,
        "protien": 25,
        "carbohydrates": 2,
        "fat": 5,
        "sodium": 20,
        "fiber": 1,
        "sugars": 10,
        "calcium": 20,
        "iron": 1.5,
        "potassium": 50,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Misti Doi",
        "calories": 150,
        "protien": 20,
        "carbohydrates": 4,
        "fat": 6,
        "sodium": 40,
        "fiber": 0,
        "sugars": 15,
        "calcium": 150,
        "iron": 0.5,
        "potassium": 100,
        "cholestrol": 30,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Misi Roti",
        "calories": 120,
        "protien": 15,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 80,
        "fiber": 2,
        "sugars": 1,
        "calcium": 30,
        "iron": 1.2,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Malapua",
        "calories": 200,
        "protien": 30,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 30,
        "fiber": 1,
        "sugars": 20,
        "calcium": 40,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Makki Di Roti Sarson Da Saag",
        "calories": 300,
        "protien": 45,
        "carbohydrates": 5,
        "fat": 10,
        "sodium": 300,
        "fiber": 5,
        "sugars": 5,
        "calcium": 60,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Maach Jhol",
        "calories": 250,
        "protien": 10,
        "carbohydrates": 20,
        "fat": 15,
        "sodium": 500,
        "fiber": 3,
        "sugars": 2,
        "calcium": 100,
        "iron": 3,
        "potassium": 300,
        "cholestrol": 80,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Lyangcha",
        "calories": 180,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 7,
        "sodium": 40,
        "fiber": 1,
        "sugars": 10,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 70,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Litti Chokha",
        "calories": 350,
        "protien": 40,
        "carbohydrates": 10,
        "fat": 15,
        "sodium": 400,
        "fiber": 6,
        "sugars": 5,
        "calcium": 80,
        "iron": 2.5,
        "potassium": 250,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Ledikeni",
        "calories": 200,
        "protien": 30,
        "carbohydrates": 3,
        "fat": 10,
        "sodium": 60,
        "fiber": 1,
        "sugars": 15,
        "calcium": 40,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 40,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Lassi",
        "calories": 200,
        "protien": 30,
        "carbohydrates": 6,
        "fat": 5,
        "sodium": 50,
        "fiber": 0,
        "sugars": 20,
        "calcium": 100,
        "iron": 0.5,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "glass"
    },
    {
        "name": "Kuzhi Paniyaram",
        "calories": 150,
        "protien": 20,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 100,
        "fiber": 1,
        "sugars": 5,
        "calcium": 40,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Kofta",
        "calories": 250,
        "protien": 20,
        "carbohydrates": 8,
        "fat": 15,
        "sodium": 300,
        "fiber": 5,
        "sugars": 5,
        "calcium": 100,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 30,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Karela Bharta",
        "calories": 100,
        "protien": 10,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 200,
        "fiber": 4,
        "sugars": 2,
        "calcium": 50,
        "iron": 1,
        "potassium": 150,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Kalakand",
        "calories": 200,
        "protien": 30,
        "carbohydrates": 5,
        "fat": 8,
        "sodium": 100,
        "fiber": 0,
        "sugars": 25,
        "calcium": 150,
        "iron": 1.5,
        "potassium": 100,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Kakinada Khaja",
        "calories": 250,
        "protien": 40,
        "carbohydrates": 3,
        "fat": 10,
        "sodium": 50,
        "fiber": 1,
        "sugars": 15,
        "calcium": 30,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Kajjikaya",
        "calories": 180,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 7,
        "sodium": 40,
        "fiber": 1,
        "sugars": 10,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 70,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Kadhi Pakoda",
        "calories": 300,
        "protien": 25,
        "carbohydrates": 10,
        "fat": 15,
        "sodium": 600,
        "fiber": 2,
        "sugars": 8,
        "calcium": 100,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 40,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Kachori",
        "calories": 300,
        "protien": 35,
        "carbohydrates": 8,
        "fat": 15,
        "sodium": 500,
        "fiber": 4,
        "sugars": 5,
        "calcium": 60,
        "iron": 2.5,
        "potassium": 250,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Jalebi",
        "calories": 200,
        "protien": 30,
        "carbohydrates": 1,
        "fat": 10,
        "sodium": 20,
        "fiber": 0,
        "sugars": 20,
        "calcium": 10,
        "iron": 0.5,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Imarti",
        "calories": 250,
        "protien": 40,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 30,
        "fiber": 0,
        "sugars": 25,
        "calcium": 20,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Gajar Ka Halwa",
        "calories": 300,
        "protien": 40,
        "carbohydrates": 5,
        "fat": 12,
        "sodium": 100,
        "fiber": 3,
        "sugars": 30,
        "calcium": 150,
        "iron": 1.5,
        "potassium": 200,
        "cholestrol": 25,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Gavvalu",
        "calories": 180,
        "protien": 25,
        "carbohydrates": 3,
        "fat": 8,
        "sodium": 20,
        "fiber": 1,
        "sugars": 10,
        "calcium": 40,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Ghevar",
        "calories": 350,
        "protien": 45,
        "carbohydrates": 5,
        "fat": 18,
        "sodium": 150,
        "fiber": 2,
        "sugars": 25,
        "calcium": 100,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 50,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Doodhpak",
        "calories": 250,
        "protien": 30,
        "carbohydrates": 6,
        "fat": 10,
        "sodium": 100,
        "fiber": 0,
        "sugars": 20,
        "calcium": 100,
        "iron": 1.5,
        "potassium": 150,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Double Ka Meetha",
        "calories": 300,
        "protien": 40,
        "carbohydrates": 5,
        "fat": 12,
        "sodium": 50,
        "fiber": 1,
        "sugars": 25,
        "calcium": 80,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 30,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Gulab Jamun",
        "calories": 150,
        "protien": 20,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 20,
        "fiber": 0,
        "sugars": 15,
        "calcium": 40,
        "iron": 0.5,
        "potassium": 80,
        "cholestrol": 10,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Dharwad Pedha",
        "calories": 200,
        "protien": 25,
        "carbohydrates": 3,
        "fat": 10,
        "sodium": 30,
        "fiber": 0,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 15,
        "Food Type": "Indian",
        "measurement": "piece"
    },
    {
        "name": "Dal Tadka",
        "calories": 250,
        "protien": 30,
        "carbohydrates": 10,
        "fat": 10,
        "sodium": 500,
        "fiber": 8,
        "sugars": 5,
        "calcium": 150,
        "iron": 2,
        "potassium": 300,
        "cholestrol": 20,
        "Food Type": "Indian",
        "measurement": "bowl"
    },
    {
        "name": "Dum Aloo",
        "calories": 350,
        "protien": 40,
        "carbohydrates": 8,
        "fat": 15,
        "sodium": 400,
        "fiber": 6,
        "sugars": 10,
        "calcium": 100,
        "iron": 2.5,
        "potassium": 250,
        "cholestrol": 0,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Daal Baati Churma",
        "calories": 400,
        "protien": 50,
        "carbohydrates": 12,
        "fat": 18,
        "sodium": 600,
        "fiber": 4,
        "sugars": 10,
        "calcium": 60,
        "iron": 2.5,
        "potassium": 400,
        "cholestrol": 15,
        "Food Type": "Indian",
        "measurement": "plate"
    },
    {
        "name": "Chole Bhature",
        "calories": 500,
        "protien": 12.5,
        "carbohydrates": 55,
        "fat": 27,
        "sodium": 650,
        "fiber": 6.5,
        "sugars": 8.6,
        "calcium": 122,
        "iron": 3.6,
        "potassium": 526.3,
        "cholestrol": "5.7",
        "Food Type": "Indian",
        "measurement": "plate"
    },
]


let recomFoods = foods.slice(0, 40)


export default recomFoods;