import axios from "axios"


axios.get("https://google.com/search/q=Hey+there")
    .then(res => console.log(res))
    .catch(err => console.error(err))

export const foods = [
    {
        "name": "Biryani",
        "calories": 202.0,
        "protien": "14 gm",
        "carbohydrates": "27 gm",
        "fat": "4.6 gm",
        "sodium": "318 mg",
        "fiber": "2.2 g",
        "sugars": "3.7 g",
        "calcium": "66.64 mg",
        "iron": "1.65 mg",
        "potassium": "502 mg",
        "cholestrol": "100mg",
        "Food Type": "Indian"
    },
    {
        "name": "Chole Bhature",
        "calories": 500.0,
        "protien": "12.5gm",
        "carbohydrates": "55gm",
        "fat": "27g",
        "sodium": "650mg",
        "fiber": "6.5g",
        "sugars": "8.6g",
        "calcium": "122mg",
        "iron": "3.6mg",
        "potassium": "526.3mg",
        "cholestrol": "5.7mg",
        "Food Type": "Indian"
    },
    {
        "name": "Jalebi",
        "calories": 150.0,
        "protien": "1.3g",
        "carbohydrates": "29g",
        "fat": "3.5g",
        "sodium": "0g",
        "fiber": "0g",
        "sugars": "19g",
        "calcium": "33mg",
        "iron": "0.2g",
        "potassium": "81.3mg",
        "cholestrol": "29g",
        "Food Type": "Indian"
    },
    {
        "name": "Naan",
        "calories": 262.0,
        "protien": "8.7g",
        "carbohydrates": "45g",
        "fat": "5.1g",
        "sodium": "1g",
        "fiber": "1.5g",
        "sugars": "3.2g",
        "calcium": "76mg",
        "iron": "2.9mg",
        "potassium": "112.5mg",
        "cholestrol": "45g",
        "Food Type": "Indian"
    },
    {
        "name": "Paneer Tikka",
        "calories": 201.0,
        "protien": "8.2g",
        "carbohydrates": "6.9g",
        "fat": "16g",
        "sodium": "41mg",
        "fiber": "2g",
        "sugars": "3.7g",
        "calcium": "224mg",
        "iron": "0.9mg",
        "potassium": "290.6mg",
        "cholestrol": "41mg",
        "Food Type": "Indian"
    },
    {
        "name": "Pani Puri",
        "calories": 152.0,
        "protien": "2.5g",
        "carbohydrates": "15g",
        "fat": "9.9g",
        "sodium": "110mg",
        "fiber": "2.2g",
        "sugars": "1.9g",
        "calcium": "14mg",
        "iron": "1mg",
        "potassium": "90.3mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Pav Bhaji",
        "calories": 390.0,
        "protien": "12g",
        "carbohydrates": "63g",
        "fat": "11g",
        "sodium": "589mg",
        "fiber": "5g",
        "sugars": "11g",
        "calcium": "124mg",
        "iron": "5.7mg",
        "potassium": "813.mg",
        "cholestrol": "50mg",
        "Food Type": "Indian"
    },
    {
        "name": "Vadapav",
        "calories": 263.0,
        "protien": "7.5g",
        "carbohydrates": "37g",
        "fat": "9.5g",
        "sodium": "209mg",
        "fiber": "3.8g",
        "sugars": "3.5g",
        "calcium": "36mg",
        "iron": "2.1mg",
        "potassium": "357.3mg",
        "cholestrol": "18mg",
        "Food Type": "Indian"
    },
    {
        "name": "Dal",
        "calories": 222.0,
        "protien": "14g",
        "carbohydrates": "34g",
        "fat": "4.2g",
        "sodium": "431mg",
        "fiber": "13g",
        "sugars": "4.5g",
        "calcium": "44mg",
        "iron": "5.8mg",
        "potassium": "713.2mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Dhokla",
        "calories": 152.0,
        "protien": "5.7g",
        "carbohydrates": "16g",
        "fat": "7.4g",
        "sodium": "310mg",
        "fiber": "2.5g",
        "sugars": "5.7g",
        "calcium": "42mg",
        "iron": "1.2mg",
        "potassium": "240.5mg",
        "cholestrol": "3.3mg",
        "Food Type": "Indian"
    },
    {
        "name": "Dosa",
        "calories": 168.0,
        "protien": "3.9g",
        "carbohydrates": "29g",
        "fat": "3.7g",
        "sodium": "94mg",
        "fiber": "0.9g",
        "sugars": "0.2g",
        "calcium": "5.7mg",
        "iron": "0.8mg",
        "potassium": "75.6mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Pakora",
        "calories": 95.0,
        "protien": "2.2g",
        "carbohydrates": "6.5g",
        "fat": "7g",
        "sodium": "180mg",
        "fiber": "1.5g",
        "sugars": "1.9g",
        "calcium": "12.5mg",
        "iron": "0.6mg",
        "potassium": "118.5mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Cucumber",
        "calories": 30.0,
        "protien": "1.3g",
        "carbohydrates": "11g",
        "fat": "0.3g",
        "sodium": "4mg",
        "fiber": "1.5g",
        "sugars": "3.4g",
        "calcium": "32mg",
        "iron": "0.6mg",
        "potassium": "295.5mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Potato",
        "calories": 161.0,
        "protien": "4.3g",
        "carbohydrates": "37g",
        "fat": "0.2g",
        "sodium": "17mg",
        "fiber": "3.8g",
        "sugars": "2g",
        "calcium": "26mg",
        "iron": "1.9mg",
        "potassium": "925.6mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Carrot",
        "calories": 16.0,
        "protien": "0.4g",
        "carbohydrates": "3.8g",
        "fat": "0.1g",
        "sodium": "27mg",
        "fiber": "1.4g",
        "sugars": "1.6g",
        "calcium": "14mg",
        "iron": "0.2mg",
        "potassium": "108.1mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Cauliflower",
        "calories": 27.0,
        "protien": "2.1g",
        "carbohydrates": "5.3g",
        "fat": "0.3g",
        "sodium": "32mg",
        "fiber": "2.1g",
        "sugars": "2g",
        "calcium": "24mg",
        "iron": "0.5mg",
        "potassium": "319.9mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Corn",
        "calories": 99.0,
        "protien": "3.5g",
        "carbohydrates": "22g",
        "fat": "1.5g",
        "sodium": "1mg",
        "fiber": "2.5g",
        "sugars": "4.7g",
        "calcium": "3.1mg",
        "iron": "0.5mg",
        "potassium": "224.5mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Water Melon",
        "calories": 86.0,
        "protien": "1.7g",
        "carbohydrates": "22g",
        "fat": "0.4g",
        "sodium": "2.9mg",
        "fiber": "1.1g",
        "sugars": "18g",
        "calcium": "20mg",
        "iron": "0.7mg",
        "potassium": "320.3mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Orange",
        "calories": 69.0,
        "protien": "1.3g",
        "carbohydrates": "18g",
        "fat": "0.2g",
        "sodium": "1.4mg",
        "fiber": "3.1g",
        "sugars": "12g",
        "calcium": "60mg",
        "iron": "0.2mg",
        "potassium": "232.4mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Pomegranate",
        "calories": 234.0,
        "protien": "4.7g",
        "carbohydrates": "53g",
        "fat": "3.3g",
        "sodium": "8.5mg",
        "fiber": "11g",
        "sugars": "39g",
        "calcium": "28mg",
        "iron": "0.9mg",
        "potassium": "665.5mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Radish",
        "calories": 16.6,
        "protien": "0.7g",
        "carbohydrates": "3.5g",
        "fat": "0g",
        "sodium": "41.4mg",
        "fiber": "1.6g",
        "sugars": "1.8g",
        "calcium": "25.3mg",
        "iron": "0.5mg",
        "potassium": "241.2mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Papaya",
        "calories": 62.0,
        "protien": "0.7g",
        "carbohydrates": "16g",
        "fat": "0.4g",
        "sodium": "12mg",
        "fiber": "2.5g",
        "sugars": "11g",
        "calcium": "29mg",
        "iron": "0.4mg",
        "potassium": "263.9mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Banana",
        "calories": 105.0,
        "protien": "1.3g",
        "carbohydrates": "27g",
        "fat": "0.4g",
        "sodium": "1.2mg",
        "fiber": "3.1g",
        "sugars": "14g",
        "calcium": "5.9mg",
        "iron": "0.3mg",
        "potassium": "422.4mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Apple",
        "calories": 95.0,
        "protien": "0.5g",
        "carbohydrates": "25g",
        "fat": "0.3g",
        "sodium": "1.8mg",
        "fiber": "4.4g",
        "sugars": "19g",
        "calcium": "11mg",
        "iron": "0.2mg",
        "potassium": "194.7mg",
        "cholestrol": "0mg",
        "Food Type": "Fruit"
    },
    {
        "name": "Tomato",
        "calories": 22.0,
        "protien": "1.1g",
        "carbohydrates": "4.8g",
        "fat": "0.3g",
        "sodium": "6.2mg",
        "fiber": "1.5g",
        "sugars": "3.2g",
        "calcium": "12mg",
        "iron": "0.3mg",
        "potassium": "291.5mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Brocolli",
        "calories": 3.5,
        "protien": "0.2g",
        "carbohydrates": "0.7g",
        "fat": "0.3g",
        "sodium": "4.1mg",
        "fiber": "0.3g",
        "sugars": "0.1g",
        "calcium": "4mg",
        "iron": "0.1mg",
        "potassium": "29.3mg",
        "cholestrol": "0mg",
        "Food Type": "Vegetable"
    },
    {
        "name": "Baked Potato",
        "calories": 161.0,
        "protien": "4.3g",
        "carbohydrates": "37g",
        "fat": "0.2gg",
        "sodium": "17mg",
        "fiber": "3.8g",
        "sugars": "2g",
        "calcium": "26mg",
        "iron": "1.9mg",
        "potassium": "925.6mg",
        "cholestrol": "0mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Burger",
        "calories": 540.0,
        "protien": "34g",
        "carbohydrates": "40g",
        "fat": "27g",
        "sodium": "791mg",
        "fiber": "0g",
        "sugars": "0g",
        "calcium": "102mg",
        "iron": "5.9mg",
        "potassium": "569.5mg",
        "cholestrol": "122mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Crispy Chicken",
        "calories": 377.0,
        "protien": "40g",
        "carbohydrates": "4.4g",
        "fat": "21g",
        "sodium": "118mg",
        "fiber": "0.1g",
        "sugars": "0g",
        "calcium": "24mg",
        "iron": "1.9mg",
        "potassium": "327.6mg",
        "cholestrol": "126mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Donut",
        "calories": 253.0,
        "protien": "3.7g",
        "carbohydrates": "29g",
        "fat": "14g",
        "sodium": "190mg",
        "fiber": "1.3g",
        "sugars": "14g",
        "calcium": "61mg",
        "iron": "1.4mg",
        "potassium": "61.2mg",
        "cholestrol": "18mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "French Fries",
        "calories": 365.0,
        "protien": "4g",
        "carbohydrates": "48g",
        "fat": "17g",
        "sodium": "246mg",
        "fiber": "4.4g",
        "sugars": "0.4g",
        "calcium": "21mg",
        "iron": "1mg",
        "potassium": "677.4mg",
        "cholestrol": "100g",
        "Food Type": "Junk Food"
    },
    {
        "name": "Hot Dog",
        "calories": 155.0,
        "protien": "5.6g",
        "carbohydrates": "1.3g",
        "fat": "14g",
        "sodium": "409mg",
        "fiber": "0g",
        "sugars": "0.6g",
        "calcium": "5.3mg",
        "iron": "0.6mg",
        "potassium": "121mg",
        "cholestrol": "28mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Pizza",
        "calories": 285.0,
        "protien": "12g",
        "carbohydrates": "36g",
        "fat": "10g",
        "sodium": "640mg",
        "fiber": "2.5g",
        "sugars": "3.8g",
        "calcium": "201mg",
        "iron": "2.7mg",
        "potassium": "184mg",
        "cholestrol": "18mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Sandwich",
        "calories": 310.0,
        "protien": "12.4g",
        "carbohydrates": "56g",
        "fat": "3.8g",
        "sodium": "590mg",
        "fiber": "4.6g",
        "sugars": "6.8g",
        "calcium": "154mg",
        "iron": "4mg",
        "potassium": "205.3mg",
        "cholestrol": "0mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Taco",
        "calories": 210.0,
        "protien": "9.4g",
        "carbohydrates": "21g",
        "fat": "9.9g",
        "sodium": "571mg",
        "fiber": "3g",
        "sugars": "1.6g",
        "calcium": "125mg",
        "iron": "1.7mg",
        "potassium": "164.2mg",
        "cholestrol": "26mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Taquito",
        "calories": 120.0,
        "protien": "3.9g",
        "carbohydrates": "14g",
        "fat": "5.3g",
        "sodium": "191mg",
        "fiber": "1.2g",
        "sugars": "0.6g",
        "calcium": "42mg",
        "iron": "1.1mg",
        "potassium": "69.1mg",
        "cholestrol": "5mg",
        "Food Type": "Junk Food"
    },
    {
        "name": "Dabeli",
        "calories": 219.0,
        "protien": "4.2g",
        "carbohydrates": "31.6g",
        "fat": "8.3g",
        "sodium": "60.6mg",
        "fiber": "0.3g",
        "sugars": "4g",
        "calcium": "26.8mg",
        "iron": "1mg",
        "potassium": "66.2mg",
        "cholestrol": "7.5mg",
        "Food Type": "Indian"
    },
    {
        "name": "Samosa",
        "calories": 261.0,
        "protien": "3.5g",
        "carbohydrates": "24g",
        "fat": "17g",
        "sodium": "423mg",
        "fiber": "2.1g",
        "sugars": "1.6g",
        "calcium": "17mg",
        "iron": "0.7mg",
        "potassium": "189.1mg",
        "cholestrol": "27mg",
        "Food Type": "Indian"
    },
    {
        "name": "Dosa",
        "calories": 168.0,
        "protien": "3.9g",
        "carbohydrates": "29g",
        "fat": "3.7g",
        "sodium": "94mg",
        "fiber": "0.9g",
        "sugars": "0.2g",
        "calcium": "5.7mg",
        "iron": "0.8mg",
        "potassium": "75.6mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Idli",
        "calories": 174.0,
        "protien": "4.8g",
        "carbohydrates": "36g",
        "fat": "1.3g",
        "sodium": "225mg",
        "fiber": "1.6g",
        "sugars": "0.3g",
        "calcium": "30mg",
        "iron": "1.8mg",
        "potassium": "123.3mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Chai",
        "calories": 4.9,
        "protien": "0.1g",
        "carbohydrates": "1.4g",
        "fat": "0.1g",
        "sodium": "0.8mg",
        "fiber": "0.3g",
        "sugars": "0g",
        "calcium": "5.9mg",
        "iron": "0.1mg",
        "potassium": "57.7mg",
        "cholestrol": "0mg",
        "Food Type": "Indian"
    },
    {
        "name": "Fried Rice",
        "calories": 279.0,
        "protien": "8g",
        "carbohydrates": "30g",
        "fat": "14g",
        "sodium": "363mg",
        "fiber": "2.1g",
        "sugars": "2.2g",
        "calcium": "37mg",
        "iron": "1.1mg",
        "potassium": "205.6mg",
        "cholestrol": "88mg",
        "Food Type": "Indian"
    },
    {
        "name": "Aloo Gobi",
        "calories": 160.0,
        "protien": 2.5,
        "carbohydrates": 10.5,
        "fat": 1,
        "sodium": 400,
        "fiber": 3,
        "sugars": 2,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 320,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Aloo Matar",
        "calories": 180.0,
        "protien": 3,
        "carbohydrates": 12,
        "fat": 1.5,
        "sodium": 350,
        "fiber": 3.5,
        "sugars": 2.5,
        "calcium": 35,
        "iron": 1.6,
        "potassium": 330,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Aloo Methi",
        "calories": 170.0,
        "protien": 2.2,
        "carbohydrates": 16,
        "fat": 5.4,
        "sodium": 300,
        "fiber": 2.8,
        "sugars": 2,
        "calcium": 40,
        "iron": 1.2,
        "potassium": 310,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Aloo Shimla Mirch",
        "calories": 150.0,
        "protien": 1.5,
        "carbohydrates": 12.8,
        "fat": 3.4,
        "sodium": 250,
        "fiber": 3.2,
        "sugars": 2.2,
        "calcium": 25,
        "iron": 1.3,
        "potassium": 300,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Aloo Tikki",
        "calories": 190.0,
        "protien": 1.8,
        "carbohydrates": 11.8,
        "fat": 5.2,
        "sodium": 350,
        "fiber": 2.5,
        "sugars": 1.5,
        "calcium": 20,
        "iron": 1,
        "potassium": 250,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Anarsa",
        "calories": 180.0,
        "protien": 30,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 10,
        "fiber": 1,
        "sugars": 20,
        "calcium": 20,
        "iron": 1,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Ariselu",
        "calories": 220.0,
        "protien": 35,
        "carbohydrates": 3,
        "fat": 9,
        "sodium": 15,
        "fiber": 2,
        "sugars": 25,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 60,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Bandar Laddu",
        "calories": 200.0,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 8,
        "sodium": 20,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": 50,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Basundi",
        "calories": 250.0,
        "protien": 35,
        "carbohydrates": 8,
        "fat": 10,
        "sodium": 100,
        "fiber": 0,
        "sugars": 30,
        "calcium": 200,
        "iron": 0.5,
        "potassium": 150,
        "cholestrol": 30,
        "Food Type": "Indian"
    },
    {
        "name": "Bhatura",
        "calories": 300.0,
        "protien": 7,
        "carbohydrates": 50,
        "fat": 10,
        "sodium": 400,
        "fiber": 2,
        "sugars": 2,
        "calcium": 40,
        "iron": 3,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Bhindi Masala",
        "calories": 161.0,
        "protien": 3.9,
        "carbohydrates": 12.1,
        "fat": 10.7,
        "sodium": 200,
        "fiber": 4,
        "sugars": 3,
        "calcium": 50,
        "iron": 1.5,
        "potassium": 300,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Biryani",
        "calories": 300.0,
        "protien": 10,
        "carbohydrates": 40,
        "fat": 10,
        "sodium": 500,
        "fiber": 3,
        "sugars": 5,
        "calcium": 100,
        "iron": 3,
        "potassium": 400,
        "cholestrol": 40,
        "Food Type": "Indian"
    },
    {
        "name": "Boondi",
        "calories": 450.0,
        "protien": 50,
        "carbohydrates": 10,
        "fat": 25,
        "sodium": 200,
        "fiber": 2,
        "sugars": 20,
        "calcium": 50,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Butter Chicken",
        "calories": 490.0,
        "protien": 30,
        "carbohydrates": 12,
        "fat": 30,
        "sodium": 600,
        "fiber": 2,
        "sugars": 6,
        "calcium": 150,
        "iron": 2,
        "potassium": 500,
        "cholestrol": 120,
        "Food Type": "Indian"
    },
    {
        "name": "Chak Hao Kheer",
        "calories": 220.0,
        "protien": 35,
        "carbohydrates": 6,
        "fat": 6,
        "sodium": 50,
        "fiber": 2,
        "sugars": 20,
        "calcium": 100,
        "iron": 1.5,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Cham Cham",
        "calories": 150.0,
        "protien": 20,
        "carbohydrates": 3,
        "fat": 7,
        "sodium": 20,
        "fiber": 0,
        "sugars": 18,
        "calcium": 40,
        "iron": 0.5,
        "potassium": 80,
        "cholestrol": 15,
        "Food Type": "Indian"
    },
    {
        "name": "Chana Masala",
        "calories": 150.0,
        "protien": 7,
        "carbohydrates": 25,
        "fat": 3,
        "sodium": 300,
        "fiber": 7,
        "sugars": 6,
        "calcium": 100,
        "iron": 3,
        "potassium": 400,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Chhena Kheeri",
        "calories": 220.0,
        "protien": 35,
        "carbohydrates": 6,
        "fat": 6,
        "sodium": 50,
        "fiber": 2,
        "sugars": 20,
        "calcium": 1.5,
        "iron": 100,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Chicken Razala",
        "calories": 150.0,
        "protien": 20,
        "carbohydrates": 3,
        "fat": 7,
        "sodium": 20,
        "fiber": 0,
        "sugars": 18,
        "calcium": 0.5,
        "iron": 40,
        "potassium": 80,
        "cholestrol": 15,
        "Food Type": "Indian"
    },
    {
        "name": "Chicken Tikka",
        "calories": 260.0,
        "protien": 30,
        "carbohydrates": 5,
        "fat": 10,
        "sodium": 500,
        "fiber": 2,
        "sugars": 2,
        "calcium": 50,
        "iron": 1.5,
        "potassium": 300,
        "cholestrol": 90,
        "Food Type": "Indian"
    },
    {
        "name": "Chicken Tikka Masala",
        "calories": 500.0,
        "protien": 30,
        "carbohydrates": 15,
        "fat": 35,
        "sodium": 600,
        "fiber": 3,
        "sugars": 6,
        "calcium": 100,
        "iron": 2,
        "potassium": 400,
        "cholestrol": 120,
        "Food Type": "Indian"
    },
    {
        "name": "Chikki",
        "calories": 150.0,
        "protien": 3,
        "carbohydrates": 20,
        "fat": 7,
        "sodium": 100,
        "fiber": 2,
        "sugars": 15,
        "calcium": 30,
        "iron": 1,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Daal Baati Churma",
        "calories": 300.0,
        "protien": 10,
        "carbohydrates": 50,
        "fat": 10,
        "sodium": 500,
        "fiber": 5,
        "sugars": 5,
        "calcium": 150,
        "iron": 4,
        "potassium": 300,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Daal Puri",
        "calories": 150.0,
        "protien": 20,
        "carbohydrates": 5,
        "fat": 5,
        "sodium": 200,
        "fiber": 2,
        "sugars": 2,
        "calcium": 30,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Unni Appam",
        "calories": 100.0,
        "protien": 15,
        "carbohydrates": 1,
        "fat": 5,
        "sodium": 10,
        "fiber": 1,
        "sugars": 10,
        "calcium": 20,
        "iron": 0.5,
        "potassium": 40,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Sutar Feni",
        "calories": 150.0,
        "protien": 25,
        "carbohydrates": 1,
        "fat": 5,
        "sodium": 10,
        "fiber": 0,
        "sugars": 15,
        "calcium": 10,
        "iron": 0.5,
        "potassium": 30,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Sohan Papdi",
        "calories": 200.0,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 10,
        "sodium": 30,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": 60,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Sohan Halwa",
        "calories": 250.0,
        "protien": 40,
        "carbohydrates": 4,
        "fat": 10,
        "sodium": 50,
        "fiber": 2,
        "sugars": 20,
        "calcium": 60,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 15,
        "Food Type": "Indian"
    },
    {
        "name": "Shrikhand",
        "calories": 465.0,
        "protien": 10,
        "carbohydrates": 60,
        "fat": 20,
        "sodium": 150,
        "fiber": 0,
        "sugars": 45,
        "calcium": 100,
        "iron": 0.5,
        "potassium": 100,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Sheera",
        "calories": 200.0,
        "protien": 4,
        "carbohydrates": 30,
        "fat": 8,
        "sodium": 150,
        "fiber": 2,
        "sugars": 20,
        "calcium": 40,
        "iron": 1.5,
        "potassium": 100,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Sheer Korma",
        "calories": 300.0,
        "protien": 45,
        "carbohydrates": 8,
        "fat": 10,
        "sodium": 150,
        "fiber": 2,
        "sugars": 35,
        "calcium": 100,
        "iron": 1.5,
        "potassium": 200,
        "cholestrol": 40,
        "Food Type": "Indian"
    },
    {
        "name": "Shankarpali",
        "calories": 120.0,
        "protien": 15,
        "carbohydrates": 2,
        "fat": 6,
        "sodium": 20,
        "fiber": 1,
        "sugars": 8,
        "calcium": 40,
        "iron": 0.5,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Sandesh",
        "calories": 350.0,
        "protien": 12,
        "carbohydrates": 45,
        "fat": 15,
        "sodium": 100,
        "fiber": 0.5,
        "sugars": 35,
        "calcium": 100,
        "iron": 0.5,
        "potassium": 100,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Rasgulla",
        "calories": 200.0,
        "protien": 5,
        "carbohydrates": 45,
        "fat": 0.5,
        "sodium": 50,
        "fiber": 0.5,
        "sugars": 35,
        "calcium": 100,
        "iron": 1,
        "potassium": 50,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Ras Malai",
        "calories": 250.0,
        "protien": 30,
        "carbohydrates": 6,
        "fat": 15,
        "sodium": 100,
        "fiber": 0,
        "sugars": 25,
        "calcium": 200,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 100,
        "Food Type": "Indian"
    },
    {
        "name": "Poornalu",
        "calories": 280.0,
        "protien": 40,
        "carbohydrates": 5,
        "fat": 10,
        "sodium": 50,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1.5,
        "potassium": 100,
        "cholestrol": 50,
        "Food Type": "Indian"
    },
    {
        "name": "Pootharekulu",
        "calories": 220.0,
        "protien": 25,
        "carbohydrates": 3,
        "fat": 12,
        "sodium": 20,
        "fiber": 0,
        "sugars": 15,
        "calcium": 30,
        "iron": 1,
        "potassium": 120,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Qubani Ka Meetha",
        "calories": 300.0,
        "protien": 60,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 50,
        "fiber": 2,
        "sugars": 40,
        "calcium": 20,
        "iron": 1.5,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Rabri",
        "calories": 250.0,
        "protien": 30,
        "carbohydrates": 8,
        "fat": 12,
        "sodium": 100,
        "fiber": 0,
        "sugars": 25,
        "calcium": 200,
        "iron": 0.5,
        "potassium": 150,
        "cholestrol": 30,
        "Food Type": "Indian"
    },
    {
        "name": "Pithe",
        "calories": 200.0,
        "protien": 35,
        "carbohydrates": 4,
        "fat": 5,
        "sodium": 100,
        "fiber": 2,
        "sugars": 15,
        "calcium": 60,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Poha",
        "calories": 250.0,
        "protien": 40,
        "carbohydrates": 6,
        "fat": 7,
        "sodium": 300,
        "fiber": 4,
        "sugars": 4,
        "calcium": 20,
        "iron": 4,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Phirni",
        "calories": 230.0,
        "protien": 35,
        "carbohydrates": 6,
        "fat": 7,
        "sodium": 100,
        "fiber": 1,
        "sugars": 20,
        "calcium": 200,
        "iron": 1,
        "potassium": 150,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Navrattan Korma",
        "calories": 300.0,
        "protien": 35,
        "carbohydrates": 10,
        "fat": 15,
        "sodium": 400,
        "fiber": 6,
        "sugars": 8,
        "calcium": 150,
        "iron": 2.5,
        "potassium": 400,
        "cholestrol": 15,
        "Food Type": "Indian"
    },
    {
        "name": "Paneer Butter Masala",
        "calories": 400.0,
        "protien": 15,
        "carbohydrates": 15,
        "fat": 30,
        "sodium": 600,
        "fiber": 3,
        "sugars": 6,
        "calcium": 300,
        "iron": 3,
        "potassium": 250,
        "cholestrol": 50,
        "Food Type": "Indian"
    },
    {
        "name": "Palak Paneer",
        "calories": 280.0,
        "protien": 12,
        "carbohydrates": 12,
        "fat": 20,
        "sodium": 500,
        "fiber": 4,
        "sugars": 4,
        "calcium": 250,
        "iron": 4,
        "potassium": 450,
        "cholestrol": 35,
        "Food Type": "Indian"
    },
    {
        "name": "Mysore Pak",
        "calories": 250.0,
        "protien": 30,
        "carbohydrates": 3,
        "fat": 15,
        "sodium": 50,
        "fiber": 1,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": "",
        "cholestrol": 50,
        "Food Type": "Indian"
    },
    {
        "name": "Naan",
        "calories": 300.0,
        "protien": 50,
        "carbohydrates": 8,
        "fat": 5,
        "sodium": 400,
        "fiber": 2,
        "sugars": 2,
        "calcium": 50,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Modak",
        "calories": 150.0,
        "protien": 25,
        "carbohydrates": 2,
        "fat": 5,
        "sodium": 20,
        "fiber": 1,
        "sugars": 10,
        "calcium": 20,
        "iron": 1.5,
        "potassium": 50,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Misti Doi",
        "calories": 150.0,
        "protien": 20,
        "carbohydrates": 4,
        "fat": 6,
        "sodium": 40,
        "fiber": 0,
        "sugars": 15,
        "calcium": 150,
        "iron": 0.5,
        "potassium": 100,
        "cholestrol": 30,
        "Food Type": "Indian"
    },
    {
        "name": "Misi Roti",
        "calories": 120.0,
        "protien": 15,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 80,
        "fiber": 2,
        "sugars": 1,
        "calcium": 30,
        "iron": 1.2,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Malapua",
        "calories": 200.0,
        "protien": 30,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 30,
        "fiber": 1,
        "sugars": 20,
        "calcium": 40,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Makki Di Roti Sarson Da Saag",
        "calories": 300.0,
        "protien": 45,
        "carbohydrates": 5,
        "fat": 10,
        "sodium": 300,
        "fiber": 5,
        "sugars": 5,
        "calcium": 60,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Maach Jhol",
        "calories": 250.0,
        "protien": 10,
        "carbohydrates": 20,
        "fat": 15,
        "sodium": 500,
        "fiber": 3,
        "sugars": 2,
        "calcium": 100,
        "iron": 3,
        "potassium": 300,
        "cholestrol": 80,
        "Food Type": "Indian"
    },
    {
        "name": "Lyangcha",
        "calories": 180.0,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 7,
        "sodium": 40,
        "fiber": 1,
        "sugars": 10,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 70,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Litti Chokha",
        "calories": 350.0,
        "protien": 40,
        "carbohydrates": 10,
        "fat": 15,
        "sodium": 400,
        "fiber": 6,
        "sugars": 5,
        "calcium": 80,
        "iron": 2.5,
        "potassium": 250,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Ledikeni",
        "calories": 200.0,
        "protien": 30,
        "carbohydrates": 3,
        "fat": 10,
        "sodium": 60,
        "fiber": 1,
        "sugars": 15,
        "calcium": 40,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 40,
        "Food Type": "Indian"
    },
    {
        "name": "Lassi",
        "calories": 200.0,
        "protien": 30,
        "carbohydrates": 6,
        "fat": 5,
        "sodium": 50,
        "fiber": 0,
        "sugars": 20,
        "calcium": 100,
        "iron": 0.5,
        "potassium": 150,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Kuzhi Paniyaram",
        "calories": 150.0,
        "protien": 20,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 100,
        "fiber": 1,
        "sugars": 5,
        "calcium": 40,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Kofta",
        "calories": 250.0,
        "protien": 20,
        "carbohydrates": 8,
        "fat": 15,
        "sodium": 300,
        "fiber": 5,
        "sugars": 5,
        "calcium": 100,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 30,
        "Food Type": "Indian"
    },
    {
        "name": "Karela Bharta",
        "calories": 100.0,
        "protien": 10,
        "carbohydrates": 3,
        "fat": 5,
        "sodium": 200,
        "fiber": 4,
        "sugars": 2,
        "calcium": 50,
        "iron": 1,
        "potassium": 150,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Kalakand",
        "calories": 200.0,
        "protien": 30,
        "carbohydrates": 5,
        "fat": 8,
        "sodium": 100,
        "fiber": 0,
        "sugars": 25,
        "calcium": 150,
        "iron": 1.5,
        "potassium": 100,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Kakinada Khaja",
        "calories": 250.0,
        "protien": 40,
        "carbohydrates": 3,
        "fat": 10,
        "sodium": 50,
        "fiber": 1,
        "sugars": 15,
        "calcium": 30,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Kajjikaya",
        "calories": 180.0,
        "protien": 25,
        "carbohydrates": 4,
        "fat": 7,
        "sodium": 40,
        "fiber": 1,
        "sugars": 10,
        "calcium": 30,
        "iron": 1.5,
        "potassium": 70,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Kadhi Pakoda",
        "calories": 300.0,
        "protien": 25,
        "carbohydrates": 10,
        "fat": 15,
        "sodium": 600,
        "fiber": 2,
        "sugars": 8,
        "calcium": 100,
        "iron": 2,
        "potassium": 200,
        "cholestrol": 40,
        "Food Type": "Indian"
    },
    {
        "name": "Kachori",
        "calories": 300.0,
        "protien": 35,
        "carbohydrates": 8,
        "fat": 15,
        "sodium": 500,
        "fiber": 4,
        "sugars": 5,
        "calcium": 60,
        "iron": 2.5,
        "potassium": 250,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Jalebi",
        "calories": 200.0,
        "protien": 30,
        "carbohydrates": 1,
        "fat": 10,
        "sodium": 20,
        "fiber": 0,
        "sugars": 20,
        "calcium": 10,
        "iron": 0.5,
        "potassium": 50,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Imarti",
        "calories": 250.0,
        "protien": 40,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 30,
        "fiber": 0,
        "sugars": 25,
        "calcium": 20,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Gajar Ka Halwa",
        "calories": 300.0,
        "protien": 40,
        "carbohydrates": 5,
        "fat": 12,
        "sodium": 100,
        "fiber": 3,
        "sugars": 30,
        "calcium": 150,
        "iron": 1.5,
        "potassium": 200,
        "cholestrol": 25,
        "Food Type": "Indian"
    },
    {
        "name": "Gavvalu",
        "calories": 180.0,
        "protien": 25,
        "carbohydrates": 3,
        "fat": 8,
        "sodium": 20,
        "fiber": 1,
        "sugars": 10,
        "calcium": 40,
        "iron": 1,
        "potassium": 80,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Ghevar",
        "calories": 350.0,
        "protien": 45,
        "carbohydrates": 5,
        "fat": 18,
        "sodium": 150,
        "fiber": 2,
        "sugars": 25,
        "calcium": 100,
        "iron": 2,
        "potassium": 150,
        "cholestrol": 50,
        "Food Type": "Indian"
    },
    {
        "name": "Doodhpak",
        "calories": 250.0,
        "protien": 30,
        "carbohydrates": 6,
        "fat": 10,
        "sodium": 100,
        "fiber": 0,
        "sugars": 20,
        "calcium": 100,
        "iron": 1.5,
        "potassium": 150,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Double Ka Meetha",
        "calories": 300.0,
        "protien": 40,
        "carbohydrates": 5,
        "fat": 12,
        "sodium": 50,
        "fiber": 1,
        "sugars": 25,
        "calcium": 80,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 30,
        "Food Type": "Indian"
    },
    {
        "name": "Gulab Jamun",
        "calories": 150.0,
        "protien": 20,
        "carbohydrates": 2,
        "fat": 8,
        "sodium": 20,
        "fiber": 0,
        "sugars": 15,
        "calcium": 40,
        "iron": 0.5,
        "potassium": 80,
        "cholestrol": 10,
        "Food Type": "Indian"
    },
    {
        "name": "Dharwad Pedha",
        "calories": 200.0,
        "protien": 25,
        "carbohydrates": 3,
        "fat": 10,
        "sodium": 30,
        "fiber": 0,
        "sugars": 20,
        "calcium": 50,
        "iron": 1,
        "potassium": 100,
        "cholestrol": 15,
        "Food Type": "Indian"
    },
    {
        "name": "Dal Tadka",
        "calories": 250.0,
        "protien": 30,
        "carbohydrates": 10,
        "fat": 10,
        "sodium": 500,
        "fiber": 8,
        "sugars": 5,
        "calcium": 150,
        "iron": 2,
        "potassium": 300,
        "cholestrol": 20,
        "Food Type": "Indian"
    },
    {
        "name": "Dum Aloo",
        "calories": 350.0,
        "protien": 40,
        "carbohydrates": 8,
        "fat": 15,
        "sodium": 400,
        "fiber": 6,
        "sugars": 10,
        "calcium": 100,
        "iron": 2.5,
        "potassium": 250,
        "cholestrol": 0,
        "Food Type": "Indian"
    },
    {
        "name": "Daal Baati Churma",
        "calories": 400.0,
        "protien": 50,
        "carbohydrates": 12,
        "fat": 18,
        "sodium": 600,
        "fiber": 4,
        "sugars": 10,
        "calcium": 60,
        "iron": 2.5,
        "potassium": 400,
        "cholestrol": 15,
        "Food Type": "Indian"
    }
]


let recomFoods = [
    ...foods
]


export default recomFoods;